IF
  Global("NTotSCSpawn","%CloakwoodMines%",0)
THEN
  RESPONSE #100
    CreateCreature("NTELITE",[215.2220],1)
    CreateCreature("NTELITE",[219.2281],1)
    CreateCreature("NTELITE",[255.2322],1)
    CreateCreature("NTELITE",[1860.1759],1)
    CreateCreature("NTELITE",[1943.1782],1)
    CreateCreature("NTELITE",[2036.1488],2)
    CreateCreature("NTELITE",[2429.1253],2)
    CreateCreature("NTELITE",[3093.658],2)
    SetGlobal("NTotSCSpawn","%CloakwoodMines%",1)
END

